# Generated by Django 4.2.5 on 2025-07-26 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import indrail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Division Code')),
                ('name', models.CharField(max_length=60, verbose_name='Division Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='Shop Name')),
                ('shop_no', models.CharField(max_length=15, verbose_name='Shop No.')),
                ('contact_no', models.CharField(max_length=15, verbose_name='Contact No.')),
                ('lat', models.CharField(max_length=30, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=30, verbose_name='Longitude')),
                ('is_open', models.BooleanField(default=False, verbose_name='Open')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_cash', models.BooleanField(default=False, verbose_name='Cash')),
                ('is_card', models.BooleanField(default=False, verbose_name='Card')),
                ('is_upi', models.BooleanField(default=False, verbose_name='UPI')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=indrail.models.upload_to_shop_image_primary, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Image')),
                ('plt1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Primary Platform')),
                ('plt2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Secondary Platform')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.org', verbose_name='Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Station Code')),
                ('name', models.CharField(max_length=100, verbose_name='Station Name')),
                ('plt', models.IntegerField(blank=True, null=True, verbose_name='No. of Platforms')),
            ],
        ),
        migrations.CreateModel(
            name='StationCat',
            fields=[
                ('cat', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Station Category')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Train No')),
                ('train_name', models.CharField(max_length=60, verbose_name='Train Name')),
                ('run_sun', models.BooleanField(default=False, null=True, verbose_name='Train runs on Sunday')),
                ('run_mon', models.BooleanField(default=False, null=True, verbose_name='Train runs on Monday')),
                ('run_tue', models.BooleanField(default=False, null=True, verbose_name='Train runs on Tuesday')),
                ('run_wed', models.BooleanField(default=False, null=True, verbose_name='Train runs on Wednesday')),
                ('run_thu', models.BooleanField(default=False, null=True, verbose_name='Train runs on Thursday')),
                ('run_fri', models.BooleanField(default=False, null=True, verbose_name='Train runs on Friday')),
                ('run_sat', models.BooleanField(default=False, null=True, verbose_name='Train runs on Saturday')),
                ('run_daily', models.BooleanField(default=False, null=True, verbose_name='Train runs Daily')),
                ('duration', models.CharField(blank=True, max_length=15, null=True, verbose_name='Duration')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_station_to', to='indrail.station', verbose_name='Station To')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_station_from', to='indrail.station', verbose_name='Station From')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Zone Code')),
                ('name', models.CharField(max_length=90, verbose_name='Zone Name')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='Station No')),
                ('dept_day', models.IntegerField(verbose_name='Departure Day')),
                ('arr_day', models.IntegerField(verbose_name='Arrival Day')),
                ('distance', models.IntegerField(verbose_name='Distance (in KMs)')),
                ('pltf', models.CharField(blank=True, max_length=6, null=True, verbose_name='Platform')),
                ('dep_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('arv_time', models.TimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('halt_time', models.TimeField(blank=True, null=True, verbose_name='Halt Time')),
                ('rev_dir', models.BooleanField(default=False, verbose_name='Reverse Direction')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.station', verbose_name='Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.train', verbose_name='Train')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indrail.stationcat', verbose_name='Station Category'),
        ),
        migrations.AddField(
            model_name='station',
            name='div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indrail.div', verbose_name='Railway Division'),
        ),
        migrations.AddField(
            model_name='station',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indrail.zone', verbose_name='Railway Zone'),
        ),
        migrations.CreateModel(
            name='ShopGst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(max_length=256, unique=True, verbose_name='Registration No.')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.orgdoc', verbose_name='GSTIN')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.shop', verbose_name='Shop Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopFssai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(max_length=256, unique=True, verbose_name='Registration No.')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('doc', models.FileField(upload_to=indrail.models.upload_to_shop_fssai, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Document')),
                ('contact_no', models.CharField(max_length=10, verbose_name='Contact No.')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.shop', verbose_name='Shop Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('join_date', models.DateField(verbose_name='Joining Date')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('org_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.orgemp', verbose_name='Org Emp')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.shop', verbose_name='Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(max_length=256, unique=True, verbose_name='Registration No.')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('doc', models.FileField(upload_to=indrail.models.upload_to_shop_lic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Document')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.shop', verbose_name='Shop Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.station', verbose_name='Railway Station'),
        ),
        migrations.AddField(
            model_name='div',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indrail.zone', verbose_name='Railway Zone'),
        ),
    ]
