# Generated by Django 4.2.5 on 2025-07-26 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='orgdoc',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.orgdoctype', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='orgdoc',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.org', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='org',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.orgtype', verbose_name='Type'),
        ),
    ]
